### ISSUE TITLE
Build on Windows Machine

### ISSUE THREAD

**Issue by ShamilSd-ux** [hlf20010508/telegram-onedrive#13]
I am first trying to build this on windows machine for testing. how to give docker commands?

**Comment by ShamilSd-ux** [comment]
Encountered these errors when building

docker compose up --build -d -t 0 && docker compose logs --tail 100 -f
[+] Building 0.0s (0/0)                                                                                              docker:default
[+] Running 1/0
 ✔ Container telegram-onedrive  Started                                                                                        0.0s 
telegram-onedrive  | Traceback (most recent call last):
telegram-onedrive  |   File "main.py", line 35, in <module>
telegram-onedrive  |     main()
telegram-onedrive  |   File "main.py", line 17, in main
telegram-onedrive  |     from modules.client import tg_bot
telegram-onedrive  |   File "/telegram-onedrive/modules/client.py", line 17, in <module>
telegram-onedrive  |     tg_bot = TelegramClient(tg_bot_session_path, tg_api_id, tg_api_hash, sequential_updates=True).start(       
telegram-onedrive  |   File "/usr/local/lib/python3.8/site-packages/telethon/client/auth.py", line 128, in start
telegram-onedrive  |     else self.loop.run_until_complete(coro)
telegram-onedrive  |   File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
telegram-onedrive  |     return future.result()
telegram-onedrive  |   File "/usr/local/lib/python3.8/site-packages/telethon/client/auth.py", line 177, in _start
telegram-onedrive  |     await self.sign_in(bot_token=bot_token)
telegram-onedrive  |   File "/usr/local/lib/python3.8/site-packages/telethon/client/auth.py", line 357, in sign_in
telegram-onedrive  |     result = await self(request)
telegram-onedrive  |   File "/usr/local/lib/python3.8/site-packages/telethon/client/users.py", line 30, in __call__
telegram-onedrive  |     return await self._call(self._sender, request, ordered=ordered)
telegram-onedrive  |   File "/usr/local/lib/python3.8/site-packages/telethon/client/users.py", line 87, in _call
telegram-onedrive  |     result = await future
telegram-onedrive  | telethon.errors.rpcerrorlist.ApiIdInvalidError: The api_id/api_hash combination is invalid (caused by ImportBotAuthorizationRequest)
telegram-onedrive  | Traceback (most recent call last):
telegram-onedrive  |   File "main.py", line 35, in <module>
telegram-onedrive  |     main()
telegram-onedrive  |   File "main.py", line 17, in main
telegram-onedrive  |     from modules.client import tg_bot
telegram-onedrive  |   File "/telegram-onedrive/modules/client.py", line 17, in <module>
telegram-onedrive  |     tg_bot = TelegramClient(tg_bot_session_path, tg_api_id, tg_api_hash, sequential_updates=True).start(       
telegram-onedrive  |   File "/usr/local/lib/python3.8/site-packages/telethon/client/auth.py", line 128, in start
telegram-onedrive  |     else self.loop.run_until_complete(coro)
telegram-onedrive  |   File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
telegram-onedrive  |     return future.result()
telegram-onedrive  |   File "/usr/local/lib/python3.8/site-packages/telethon/client/auth.py", line 177, in _start
telegram-onedrive  |     await self.sign_in(bot_token=bot_token)
telegram-onedrive  |   File "/usr/local/lib/python3.8/site-packages/telethon/client/auth.py", line 357, in sign_in
telegram-onedrive  |     result = await self(request)
telegram-onedrive  |   File "/usr/local/lib/python3.8/site-packages/telethon/client/users.py", line 30, in __call__
telegram-onedrive  |     return await self._call(self._sender, request, ordered=ordered)
telegram-onedrive  |   File "/usr/local/lib/python3.8/site-packages/telethon/client/users.py", line 87, in _call
telegram-onedrive  |     result = await future
telegram-onedrive  | telethon.errors.rpcerrorlist.ApiIdInvalidError: The api_id/api_hash combination is invalid (caused by ImportBotAuthorizationRequest)
telegram-onedrive  | Traceback (most recent call last):
telegram-onedrive  |   File "main.py", line 35, in <module>
telegram-onedrive  |     main()
telegram-onedrive  |   File "main.py", line 17, in main
telegram-onedrive  |     from modules.client import tg_bot
telegram-onedrive  |   File "/telegram-onedrive/modules/client.py", line 17, in <module>
telegram-onedrive  |     tg_bot = TelegramClient(tg_bot_session_path, tg_api_id, tg_api_hash, sequential_updates=True).start(       
telegram-onedrive  |   File "/usr/local/lib/python3.8/site-packages/telethon/client/auth.py", line 128, in start
telegram-onedrive  |     else self.loop.run_until_complete(coro)
telegram-onedrive  |   File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
telegram-onedrive  |     return future.result()
telegram-onedrive  |   File "/usr/local/lib/python3.8/site-packages/telethon/client/auth.py", line 177, in _start
telegram-onedrive  |     await self.sign_in(bot_token=bot_token)
telegram-onedrive  |   File "/usr/local/lib/python3.8/site-packages/telethon/client/auth.py", line 357, in sign_in
telegram-onedrive  |     result = await self(request)
telegram-onedrive  |   File "/usr/local/lib/python3.8/site-packages/telethon/client/users.py", line 30, in __call__
telegram-onedrive  |     return await self._call(self._sender, request, ordered=ordered)
telegram-onedrive  |   File "/usr/local/lib/python3.8/site-packages/telethon/client/users.py", line 87, in _call
telegram-onedrive  |     result = await future
telegram-onedrive  | telethon.errors.rpcerrorlist.ApiIdInvalidError: The api_id/api_hash combination is invalid (caused by ImportBotAuthorizationRequest)
telegram-onedrive  | Traceback (most recent call last):
telegram-onedrive  |   File "main.py", line 35, in <module>
telegram-onedrive  |     main()
telegram-onedrive  |   File "main.py", line 17, in main
telegram-onedrive  |     from modules.client import tg_bot
telegram-onedrive  |   File "/telegram-onedrive/modules/client.py", line 17, in <module>
telegram-onedrive  |     tg_bot = TelegramClient(tg_bot_session_path, tg_api_id, tg_api_hash, sequential_updates=True).start(       
telegram-onedrive  |   File "/usr/local/lib/python3.8/site-packages/telethon/client/auth.py", line 128, in start
telegram-onedrive  |     else self.loop.run_until_complete(coro)
telegram-onedrive  |   File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
telegram-onedrive  |     return future.result()
telegram-onedrive  |   File "/usr/local/lib/python3.8/site-packages/telethon/client/auth.py", line 177, in _start
telegram-onedrive  |     await self.sign_in(bot_token=bot_token)
telegram-onedrive  |   File "/usr/local/lib/python3.8/site-packages/telethon/client/auth.py", line 357, in sign_in
telegram-onedrive  |     result = await self(request)
telegram-onedrive  |   File "/usr/local/lib/python3.8/site-packages/telethon/client/users.py", line 30, in __call__
telegram-onedrive  |     return await self._call(self._sender, request, ordered=ordered)
telegram-onedrive  |   File "/usr/local/lib/python3.8/site-packages/telethon/client/users.py", line 87, in _call
telegram-onedrive  |     result = await future
telegram-onedrive  | telethon.errors.rpcerrorlist.ApiIdInvalidError: The api_id/api_hash combination is invalid (caused by ImportBotAuthorizationRequest)
telegram-onedrive  | Traceback (most recent call last):
telegram-onedrive  |   File "main.py", line 35, in <module>
telegram-onedrive  |     main()
telegram-onedrive  |   File "main.py", line 17, in main
telegram-onedrive  |     from modules.client import tg_bot
telegram-onedrive  |   File "/telegram-onedrive/modules/client.py", line 17, in <module>
telegram-onedrive  |     tg_bot = TelegramClient(tg_bot_session_path, tg_api_id, tg_api_hash, sequential_updates=True).start(       
telegram-onedrive  |   File "/usr/local/lib/python3.8/site-packages/telethon/client/auth.py", line 128, in start
telegram-onedrive  |     else self.loop.run_until_complete(coro)
telegram-onedrive  |   File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
telegram-onedrive  |     return future.result()
telegram-onedrive  |   File "/usr/local/lib/python3.8/site-packages/telethon/client/auth.py", line 177, in _start
telegram-onedrive  |     await self.sign_in(bot_token=bot_token)
telegram-onedrive  |   File "/usr/local/lib/python3.8/site-packages/telethon/client/auth.py", line 357, in sign_in
telegram-onedrive  |     result = await self(request)
telegram-onedrive  |   File "/usr/local/lib/python3.8/site-packages/telethon/client/users.py", line 30, in __call__
telegram-onedrive  |     return await self._call(self._sender, request, ordered=ordered)
telegram-onedrive  |   File "/usr/local/lib/python3.8/site-packages/telethon/client/users.py", line 87, in _call
telegram-onedrive  |     result = await future
telegram-onedrive  | telethon.errors.rpcerrorlist.ApiIdInvalidError: The api_id/api_hash combination is invalid (caused by ImportBotAuthorizationRequest)

**Comment by hlf20010508** [comment]
Read [Launch Through Docker](https://github.com/hlf20010508/telegram-onedrive#launch-through-docker) at the bottom of readme, and you'll find the command.

You're not building, there's no build configuration written in docker-compose.yml.

You're actually using my image.

And the error log says your `tg_api_id` and `tg_api_hash` is wrong.

I don't think it's a good idea for you to build it.

Please make sure you can access azure portal first, or everything will be in vain.

**Comment by ShamilSd-ux** [comment]
This is my config. is the format compatible?

![config](https://github.com/hlf20010508/telegram-onedrive/assets/81691084/a4613ef6-77c9-4c1b-8156-6eaf98092f37)

**Comment by hlf20010508** [comment]
```yml
version: '3'
services:
  telegram-onedrive:
    container_name: telegram-onedrive
    image: hlf01/telegram-onedrive
    restart: always
    ports:
      - 8080:8080
    environment:
      - server_uri=https://127.0.0.1:8080
      - tg_bot_token=64xxxxxxxx:yyyyyyyyyyyyyyyyyyyy
      - tg_api_id=241xxxxx
      - tg_api_hash=6b1xxxxxxxxxxxxxxxxxxxxx
      - tg_user_phone=+9xxxxxxxxx
      - tg_user_name=syxxxxxxxxx
      - od_client_id=e645dxxxxxxxxxxxxxxxxxxxxxx
      - od_client_secret=N1b8Q~xxxxxxxxxxxxxxxxxxxxxx
      - remote_root_path=/MyOneDriveX
      - delete_flag=false
    command: python main.py
```

**Comment by hlf20010508** [comment]
And make sure your `redirect uri` on azure portal is `https://127.0.0.1:8080/auth`.

**Comment by ShamilSd-ux** [comment]
![image](https://github.com/hlf20010508/telegram-onedrive/assets/81691084/af079f54-41ed-447f-ad70-7edceb44ba8d)
![image](https://github.com/hlf20010508/telegram-onedrive/assets/81691084/05106959-4909-46da-8d08-5cb6bb8d4729)

Thanks a lot for guidance. Bot is running and  This is the progress. The web page is not responding...

**Comment by hlf20010508** [comment]
you wrote
```yml
ports:
  - 8080:8080
```
in your docker-compose.yml right?

**Comment by hlf20010508** [comment]
And did you visit `http://127.0.0.1:8080`, not `https://127.0.0.1:8080`?

**Comment by ShamilSd-ux** [comment]
Yeah other bots i.e youtube downloaders are running on that ports. Can i use same ports or use which ones!?. please suggest...

**Comment by hlf20010508** [comment]
Use an alternate one.
set port reflection to `xxxx:8080`, and set your `server_uri` to `https://127.0.0.1:xxxx`, and set `redirect uri` on azure portal to `https://127.0.0.1:xxxx/auth`.
`xxxx` is your alternate port.

**Comment by hlf20010508** [comment]
Make sure you're using the latest docker image.

**Comment by ShamilSd-ux** [comment]
I am using 8000. Is that good enough?. so i have to give 8000:8080 in config!?

**Comment by hlf20010508** [comment]
Yeah, as long as your `8000` is not occupied by other apps.

**Comment by ShamilSd-ux** [comment]
![image](https://github.com/hlf20010508/telegram-onedrive/assets/81691084/8b73acb5-496f-4693-8354-e525da54a80b)
![client](https://github.com/hlf20010508/telegram-onedrive/assets/81691084/17fb9a77-7451-4d81-a691-b7e5e9023924)
Still not working. WHy!?

**Comment by ShamilSd-ux** [comment]
![image](https://github.com/hlf20010508/telegram-onedrive/assets/81691084/0db340a4-ecb1-4127-b953-66e68547a2b6)

**Comment by hlf20010508** [comment]
Run `docker compose pull` to get the latest image, and try again.

**Comment by ShamilSd-ux** [comment]
![image](https://github.com/hlf20010508/telegram-onedrive/assets/81691084/e146d5ea-f4a5-4294-ab84-d7f39962a72f)
These are the logs . I don't know why the page is not responding...

**Comment by ShamilSd-ux** [comment]
I have deleted other containers and set the port to 8080

**Comment by hlf20010508** [comment]
It shows that the auth server run successfully.
Remove your container.
Then run `netstat -aon|findstr "8080"` to check if `8080` is occupied by any apps.
![image](https://github.com/hlf20010508/telegram-onedrive/assets/76218469/c657b58c-f77d-4196-9477-c027bfb07475)
In the example image, `8081` is its port, `9088` is its pid.
Take a screenshot, and send it here.

**Comment by ShamilSd-ux** [comment]
![image](https://github.com/hlf20010508/telegram-onedrive/assets/81691084/c0c45c77-4c31-4909-b149-b7adc2242960)
I have done as mentioned

**Comment by hlf20010508** [comment]
You're using Edge right?
I've googled it, it says that Edge doesn't support `127.0.0.1` or `localhost` by default.
You need to change a browser, such as Firefox or Chrome.
If you insist to use Edge, run `CheckNetIsolation LoopbackExempt -a -n=Microsoft.MicrosoftEdge_8wekyb3d8bbwe`.

**Comment by ShamilSd-ux** [comment]
![image](https://github.com/hlf20010508/telegram-onedrive/assets/81691084/585caf92-55bb-48ea-8a87-0363707f6956)
![image](https://github.com/hlf20010508/telegram-onedrive/assets/81691084/508f36c3-c55b-4d5e-a899-ecdcbf61162b)
This is the problem in firefox

**Comment by ShamilSd-ux** [comment]
while in docker
![image](https://github.com/hlf20010508/telegram-onedrive/assets/81691084/3236ddb5-66aa-4a16-aeb2-076256ddcd2f)

**Comment by ShamilSd-ux** [comment]
This is the only container running
![image](https://github.com/hlf20010508/telegram-onedrive/assets/81691084/66e0cadf-e5c6-4adf-8bc3-c3b3401e4942)

**Comment by hlf20010508** [comment]
![](https://private-user-images.githubusercontent.com/81691084/292852927-585caf92-55bb-48ea-8a87-0363707f6956.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1ODYxOTksIm5iZiI6MTcwMzU4NTg5OSwicGF0aCI6Ii84MTY5MTA4NC8yOTI4NTI5MjctNTg1Y2FmOTItNTViYi00OGVhLThhODctMDM2MzcwN2Y2OTU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI2VDEwMTgxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI2Y2E1NDgwNzRlNzAwMzQ1ODhmZDEzNGNhYzFmNWM3ODg0OGJmZGNkMTMzMzIzNTJkYjY3ZDg5OTk3ZDdmMjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zM27uSfeO60WG3KtYX_vltpCiYGV59k1gDqDCxTieYg)
This says you're using `network_mode: host`.
This is not supported on windows.

**Comment by hlf20010508** [comment]
Remove `network_mode: host` and try again.

**Comment by ShamilSd-ux** [comment]
Yay Got it now but telegram is not sending login code messages. I have tried so many times today

![image](https://github.com/hlf20010508/telegram-onedrive/assets/81691084/f56021a8-ab66-4891-a935-465cc92763f7)

**Comment by hlf20010508** [comment]
The code is sent in Telegram app, not SMS.
If you can't receive it in Telegram app, check if your `tg_user_phone` is correct.
If they are all good, I don't know what to do.

**Comment by hlf20010508** [comment]
It looks like this:
![image](https://github.com/hlf20010508/telegram-onedrive/assets/76218469/34815242-8b7d-4bf6-aedf-7ffa3bf64e66)

**Comment by ShamilSd-ux** [comment]
Previously i used to get those when page is not working. Now when page is working those codes are not coming even though i changed mobile number with all parameters...

**Comment by hlf20010508** [comment]
Then I think you can try using the previous code. The new code may not always be sent if you hasn't used the old one.

**Comment by ShamilSd-ux** [comment]
Telegram has blocked codes on my Ip. I have generated 10 codes today without using them. I think the telegram will reset after 24 hours. So lets  try tommorrow. Thanks a lot...

**Comment by hlf20010508** [comment]
Ok.

**Comment by ShamilSd-ux** [comment]
After your latest update I have got this
![293062843-028904c2-1a15-4e26-90a2-c146682d54b9](https://github.com/hlf20010508/telegram-onedrive/assets/81691084/01410080-eeb0-45ca-b6b5-dd63aebe06ba)
Look at this please.

**Comment by hlf20010508** [comment]
Ok, it's a bug. Try version 3.9.1. I'll fix this bug.

**Comment by hlf20010508** [comment]
Set image to hlf01/telegram-onedrive:3.9.1

**Comment by ShamilSd-ux** [comment]
Will it take time. Yester I got  this issue and foolish i posted that in my own fork...😂. Your latest version inspired me...

**Comment by hlf20010508** [comment]
Did you enabled two-step verification in telegram?
If not, 3.9.1 should work for you.
If you enabled, you need to set tg_user_password in docker-compose.yml. See Preparation point 8 in readme.
![image](https://github.com/hlf20010508/telegram-onedrive/assets/76218469/2548b9fb-7942-47fd-b3c0-6f7e437b9afe)

**Comment by ShamilSd-ux** [comment]
Alhamdulillah. Today it is successful after many hurdles. Many more thanks to You❤️ Can I add the bot to as many groups I wish!?

**Comment by hlf20010508** [comment]
I don't recommend you to do so, because this bot is designed for private group. I don't know what problem you'll face if you use it in a public group.
And this bot can only handle one transfer at a time.

**Comment by hlf20010508** [comment]
So, using it in just one private group is what you should do.

**Comment by ShamilSd-ux** [comment]
Can i have your telegram Id to discuss in private...

**Comment by hlf20010508** [comment]
No. But you can email me.

**Comment by ShamilSd-ux** [comment]
Got it. I have sent you a mail. kindly reply asap

**Comment by hlf20010508** [comment]
I need to have a test again.
According to my previous tests, channels are not supported.

**Comment by ShamilSd-ux** [comment]
I am getting numbers as file name in onedrive. Why?

**Comment by hlf20010508** [comment]
Yes it is. To prevent files with the same name be overwritten.

**Comment by ShamilSd-ux** [comment]
Every file name would be unique. How can we identify which file we want. please change that...

**Comment by hlf20010508** [comment]
No. Your files' names are unique, but other people's may not.
But that's a good point, I think I can set a command for using file's real name.

**Comment by ShamilSd-ux** [comment]
please do that now . I am planning to sync today

**Comment by hlf20010508** [comment]
No, it takes time. Be patient.

**Comment by hlf20010508** [comment]
I've tested it, it doesn't support channel. The bot can't receive message in channel.

**Comment by ShamilSd-ux** [comment]
Every file name would be unique. How can we identify which file we want. Guide me at which parts to change the code...

**Comment by hlf20010508** [comment]
Ok, try the latest version.
I've fix the bug, and use file's real name. If there are files with the same name, one of them will be renamed automatically by OneDrive.

**Comment by ShamilSd-ux** [comment]
Very Good Approach... Do I have to delete the container and start the process again!?

**Comment by ShamilSd-ux** [comment]
The bug is still there 

![image](https://github.com/hlf20010508/telegram-onedrive/assets/81691084/7c126cc5-11a6-4b3e-af39-11d4593b7a22)

**Comment by ShamilSd-ux** [comment]
![image](https://github.com/hlf20010508/telegram-onedrive/assets/81691084/0977df31-3b6c-4ba5-be06-47cc8f269778)

**Comment by ShamilSd-ux** [comment]
I have edited to this  **image: hlf01/telegram-onedrive:3.10.1** in config and it went well. Thanks. You should correct the default image.

**Comment by hlf20010508** [comment]
You need to use `docker compose pull` to overwrite the latest image stored in you machine.

**Comment by ShamilSd-ux** [comment]
Can we add the bot to multiple groups and multiple users?

**Comment by hlf20010508** [comment]
If you're the owner of the group, yes you can. Otherwise, no.
By the way, using files's real name caused a big trouble, I have to handle it.

**Comment by ShamilSd-ux** [comment]
What's the trouble!?. You can give duplicates with _2 or _copy at end of file name as it occurs in windows duplicate files. Do you abrogated that feature in latest update!?. And Adding bot to other groups is useless as the bot remains non-responsive in latter groups...

**Comment by hlf20010508** [comment]
OneDrive has some limitations on some characters to be used in file name.
If you add the bot to a group, and you're not the owner of that group, you can't set the bot as admin, that's why it doesn't reapond.

**Comment by ShamilSd-ux** [comment]
I will add bot to the group if I am the owner of the group. I knew basics buddy but I am struggling for coding to improve my professional and personal projects in telegram and UIPath.

**Comment by hlf20010508** [comment]
I've introduced a preprocessing function for file name in `3.10.3`.

**Comment by ShamilSd-ux** [comment]
How to make bot accessible to other users?

**Comment by hlf20010508** [comment]
Delete `tg_user_name` in your `yml`.

**Comment by ShamilSd-ux** [comment]
I want only specific users to access the bot.

**Comment by hlf20010508** [comment]
See Preparation point 9,

**Comment by ShamilSd-ux** [comment]
Can we allot multiple folders in onedrive to the bot

**Comment by hlf20010508** [comment]
`/dir` and its sub commands.
Use `/help` to see details.

**Comment by ShamilSd-ux** [comment]
Error: Traceback (most recent call last):
  File "/telegram-onedrive/modules/handlers/transfer.py", line 43, in transfer_handler
    onedrive.stream_upload(buffer, name)
  File "/telegram-onedrive/modules/onedrive/init.py", line 88, in stream_upload
    request.send(data=buffer)
  File "/usr/local/lib/python3.8/site-packages/onedrivesdk/request_base.py", line 132, in send
    self._client.auth_provider.authenticate_request(self)
  File "/telegram-onedrive/modules/onedrive/_rewrite.py", line 71, in authenticate_request
    self.refresh_token()
  File "/usr/local/lib/python3.8/site-packages/onedrivesdk/auth_provider.py", line 263, in refresh_token
    self._session.refresh_session(rcont["expires_in"],
KeyError: 'expires_in'



This is the error that occurred recently



![image](https://github.com/hlf20010508/telegram-onedrive/assets/81691084/2b2f868e-4703-4f59-ae8b-3f82adb4947d)
