### ISSUE TITLE
auth问题

### ISSUE THREAD

**Issue by dadaoerv** [hlf20010508/telegram-onedrive#20]
感谢大佬的项目，遇到一些问题：
log：
Traceback (most recent call last):
  File "main.py", line 35, in <module>
    main()
  File "main.py", line 17, in main
    from modules.client import tg_bot
  File "/telegram-onedrive/modules/client.py", line 10, in <module>
    from modules.onedrive import Onedrive
  File "/telegram-onedrive/modules/onedrive/__init__.py", line 20, in <module>
    from modules.onedrive.utils import Dir
  File "/telegram-onedrive/modules/onedrive/utils.py", line 9, in <module>
    from modules.env import remote_root_path
  File "/telegram-onedrive/modules/env.py", line 17, in <module>
    tg_user_name = os.environ.get("tg_user_name", None).split(',')
AttributeError: 'NoneType' object has no attribute 'split'
Traceback (most recent call last):
  File "main.py", line 35, in <module>
    main()
  File "main.py", line 17, in main
    from modules.client import tg_bot
  File "/telegram-onedrive/modules/client.py", line 10, in <module>
    from modules.onedrive import Onedrive
  File "/telegram-onedrive/modules/onedrive/__init__.py", line 20, in <module>
    from modules.onedrive.utils import Dir
  File "/telegram-onedrive/modules/onedrive/utils.py", line 9, in <module>
    from modules.env import remote_root_path
  File "/telegram-onedrive/modules/env.py", line 17, in <module>
    tg_user_name = os.environ.get("tg_user_name", None).split(',')
AttributeError: 'NoneType' object has no attribute 'split'
Traceback (most recent call last):
  File "main.py", line 35, in <module>
    main()
  File "main.py", line 17, in main
    from modules.client import tg_bot
  File "/telegram-onedrive/modules/client.py", line 10, in <module>
    from modules.onedrive import Onedrive
  File "/telegram-onedrive/modules/onedrive/__init__.py", line 20, in <module>
    from modules.onedrive.utils import Dir
  File "/telegram-onedrive/modules/onedrive/utils.py", line 9, in <module>
    from modules.env import remote_root_path
  File "/telegram-onedrive/modules/env.py", line 17, in <module>
    tg_user_name = os.environ.get("tg_user_name", None).split(',')
AttributeError: 'NoneType' object has no attribute 'split'
Traceback (most recent call last):
  File "main.py", line 35, in <module>
    main()
  File "main.py", line 17, in main
    from modules.client import tg_bot
  File "/telegram-onedrive/modules/client.py", line 10, in <module>
    from modules.onedrive import Onedrive
  File "/telegram-onedrive/modules/onedrive/__init__.py", line 20, in <module>
    from modules.onedrive.utils import Dir
  File "/telegram-onedrive/modules/onedrive/utils.py", line 9, in <module>
    from modules.env import remote_root_path
  File "/telegram-onedrive/modules/env.py", line 17, in <module>
    tg_user_name = os.environ.get("tg_user_name", None).split(',')
AttributeError: 'NoneType' object has no attribute 'split'
Traceback (most recent call last):
  File "main.py", line 35, in <module>
    main()
  File "main.py", line 17, in main
    from modules.client import tg_bot
  File "/telegram-onedrive/modules/client.py", line 10, in <module>
    from modules.onedrive import Onedrive
  File "/telegram-onedrive/modules/onedrive/__init__.py", line 20, in <module>
    from modules.onedrive.utils import Dir
  File "/telegram-onedrive/modules/onedrive/utils.py", line 9, in <module>
    from modules.env import remote_root_path
  File "/telegram-onedrive/modules/env.py", line 17, in <module>
    tg_user_name = os.environ.get("tg_user_name", None).split(',')
AttributeError: 'NoneType' object has no attribute 'split'
Traceback (most recent call last):
  File "main.py", line 35, in <module>
    main()
  File "main.py", line 17, in main
    from modules.client import tg_bot
  File "/telegram-onedrive/modules/client.py", line 10, in <module>
    from modules.onedrive import Onedrive
  File "/telegram-onedrive/modules/onedrive/__init__.py", line 20, in <module>
    from modules.onedrive.utils import Dir
  File "/telegram-onedrive/modules/onedrive/utils.py", line 9, in <module>
    from modules.env import remote_root_path
  File "/telegram-onedrive/modules/env.py", line 17, in <module>
    tg_user_name = os.environ.get("tg_user_name", None).split(',')
AttributeError: 'NoneType' object has no attribute 'split'
Traceback (most recent call last):
  File "main.py", line 35, in <module>
    main()
  File "main.py", line 17, in main
    from modules.client import tg_bot
  File "/telegram-onedrive/modules/client.py", line 10, in <module>
    from modules.onedrive import Onedrive
  File "/telegram-onedrive/modules/onedrive/__init__.py", line 20, in <module>
    from modules.onedrive.utils import Dir
  File "/telegram-onedrive/modules/onedrive/utils.py", line 9, in <module>
    from modules.env import remote_root_path
  File "/telegram-onedrive/modules/env.py", line 17, in <module>
    tg_user_name = os.environ.get("tg_user_name", None).split(',')
AttributeError: 'NoneType' object has no attribute 'split'

我是直接在1panel进行的反代，azure填的回调域名是：https://od.example.com/auth  
有尝试过ip：端口，https://域名：端口，都是同样的错误。

**Comment by dadaoerv** [comment]
上述有调整过域名，ip，端口，都在azure的应用里相应的修改。

**Comment by hlf20010508** [comment]
`tg_user_name = os.environ.get("tg_user_name", None).split(',')`
这句的问题，你没有填写`tg_user_name `。
不过我这个是可选项，所以这是个bug，我等会修一下。

**Comment by hlf20010508** [comment]
修复了，用`hlf01/telegram-onedrive:dev`镜像试试。
但是我还是建议填写`tg_user_name`。
如果还有问题，可以发完整的配置和azure上的链接过来，用xxxx代替敏感部分。
