### ISSUE TITLE
你尝试过转存3GB以上的视频吗？

### ISSUE THREAD

**Issue by wangkingsten** [hlf20010508/telegram-onedrive#21]
`Error: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 793, in urlopen
    response = self._make_request(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 537, in _make_request
    response = conn.getresponse()
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 466, in getresponse
    httplib_response = super().getresponse()
  File "/usr/local/lib/python3.8/http/client.py", line 1348, in getresponse
    response.begin()
  File "/usr/local/lib/python3.8/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.8/http/client.py", line 285, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 847, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/retry.py", line 470, in increment
    raise reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 793, in urlopen
    response = self._make_request(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 537, in _make_request
    response = conn.getresponse()
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 466, in getresponse
    httplib_response = super().getresponse()
  File "/usr/local/lib/python3.8/http/client.py", line 1348, in getresponse
    response.begin()
  File "/usr/local/lib/python3.8/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.8/http/client.py", line 285, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/telegram-onedrive/modules/handlers/transfer.py", line 33, in transfer_handler
    response_dict = await multi_parts_uploader(tg_client, message.media.document, name, progress_callback=callback)
  File "/telegram-onedrive/modules/transfer.py", line 66, in multi_parts_uploader
    response_dict = await onedrive.multipart_upload(uploader, buffer, pre_offset)
  File "/telegram-onedrive/modules/onedrive/init.py", line 106, in multipart_upload
    response = uploader.post(offset, part_size, buffer)
  File "/telegram-onedrive/modules/onedrive/init.py", line 259, in post
    return self.request(begin, length, buffer, options).post()
  File "/telegram-onedrive/modules/onedrive/init.py", line 205, in post
    entity = UploadSession(json.loads(self.send(data=self._buffer).content))
  File "/usr/local/lib/python3.8/site-packages/onedrivesdk/request_base.py", line 147, in send
    response = self._client.http_provider.send(
  File "/usr/local/lib/python3.8/site-packages/onedrivesdk/http_provider.py", line 69, in send
    response = session.send(prepped)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))`

我试过很多次了，唯独一个3GB以上的视频会报错
是超出了单个文件的空间限制还是上传时间太久，超过了每次认证的时限

**Comment by hlf20010508** [comment]
我没有见过2GB以上的文件，因为没有VIP的话只能上传2GB的，所以没有机会测试。
如果可以的话，你可以提供一下文件的链接。
如果这种2GB的文件本身无法用telethon下载的话就没有办法了。

**Comment by wangkingsten** [comment]
比如说：https://t.me/HHZJIZHONGYING/17394
：）

**Comment by hlf20010508** [comment]
好的我去测试一下

**Comment by hlf20010508** [comment]
可以上传，没有问题。
可能是你的网络问题。
![image](https://github.com/hlf20010508/telegram-onedrive/assets/76218469/d37128c2-ef17-4360-a93c-b0debeccc6f4)
