### ISSUE TITLE
Error: Traceback (most recent call last):

### ISSUE THREAD

**Issue by ShamilSd-ux** [hlf20010508/telegram-onedrive#22]
Error: Traceback (most recent call last):
  File "/telegram-onedrive/modules/handlers/transfer.py", line 43, in transfer_handler
    onedrive.stream_upload(buffer, name)
  File "/telegram-onedrive/modules/onedrive/init.py", line 88, in stream_upload
    request.send(data=buffer)
  File "/usr/local/lib/python3.8/site-packages/onedrivesdk/request_base.py", line 132, in send
    self._client.auth_provider.authenticate_request(self)
  File "/telegram-onedrive/modules/onedrive/_rewrite.py", line 71, in authenticate_request
    self.refresh_token()
  File "/usr/local/lib/python3.8/site-packages/onedrivesdk/auth_provider.py", line 263, in refresh_token
    self._session.refresh_session(rcont["expires_in"],
KeyError: 'expires_in'

This is the error that occurred recently

![image](https://github.com/hlf20010508/telegram-onedrive/assets/81691084/2b2f868e-4703-4f59-ae8b-3f82adb4947d)

_Originally posted by @ShamilSd-ux in https://github.com/hlf20010508/telegram-onedrive/issues/13#issuecomment-2063150874_

**Comment by hlf20010508** [comment]
Recreate container and try again.
Here it works fine.
It felt like it was your network problem.
