### ISSUE TITLE
unable to complete tg auth

### ISSUE THREAD

**Issue by Pooranji** [hlf20010508/telegram-onedrive#23]
tg auth is giving error
this is the error that i am getting from bot 
Traceback (most recent call last):
  File "/telegram-onedrive/modules/handlers/[auth.py](https://web.telegram.org/a/auth.py)", line 126, in auth_handler
    _tg_client = await tg_client.start(
  File "/usr/local/lib/python3.8/site-packages/telethon/client/auth.py", line 184, in _start
    await self.send_code_request(phone, force_sms=force_sms)
  File "/usr/local/lib/python3.8/site-packages/telethon/client/auth.py", line 434, in send_code_request
    result = await self(functions.auth.SendCodeRequest(
  File "/usr/local/lib/python3.8/site-packages/telethon/client/users.py", line 30, in call
    return await self._call(self._sender, request, ordered=ordered)
  File "/usr/local/lib/python3.8/site-packages/telethon/client/users.py", line 67, in _call
    future = sender.send(request, ordered=ordered)
  File "/usr/local/lib/python3.8/site-packages/telethon/network/mtprotosender.py", line 183, in send
    state = RequestState(request)
  File "/usr/local/lib/python3.8/site-packages/telethon/network/requeststate.py", line 17, in init
    [self.data](https://web.telegram.org/a/self.data) = bytes(request)
  File "/usr/local/lib/python3.8/site-packages/telethon/tl/tlobject.py", line 194, in bytes
    return self._bytes()
  File "/usr/local/lib/python3.8/site-packages/telethon/tl/functions/auth.py", line 641, in _bytes
    self.serialize_bytes(self.phone_number),
  File "/usr/local/lib/python3.8/site-packages/telethon/tl/tlobject.py", line 112, in serialize_bytes
    raise TypeError(
TypeError: bytes or str expected, not <class 'NoneType'>

**Comment by hlf20010508** [comment]
I think this probably because your `tg_user_phone` is not correct.
Is there a space between `=` and your phone number?
It's better to show your docker-compose.yml.
Replace sensitive information with `xxxxxx`.

**Comment by hlf20010508** [comment]
See [this](https://github.com/hlf20010508/telegram-onedrive/issues/13#issuecomment-1869315121) as an example.

**Comment by steady298** [comment]
> See [this](https://github.com/hlf20010508/telegram-onedrive/issues/13#issuecomment-1869315121) as an example.

i have the same issue,and this is my yaml,
![Uploading {1284B9E3-7212-43d2-AD62-3D1F3E0A0265}.png…]()

**Comment by hlf20010508** [comment]
> i have the same issue,and this is my yaml, <img alt="{1284B9E3-7212-43d2-AD62-3D1F3E0A0265}" width="743" src="https://private-user-images.githubusercontent.com/115759238/329551583-10078e36-7c28-4603-9e34-d35b64616a44.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzNDQ1ODAsIm5iZiI6MTcxNTM0NDI4MCwicGF0aCI6Ii8xMTU3NTkyMzgvMzI5NTUxNTgzLTEwMDc4ZTM2LTdjMjgtNDYwMy05ZTM0LWQzNWI2NDYxNmE0NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMFQxMjMxMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMGE1MGUyZjJiZjVkNjNjZjVmN2NlYTRjMTAwMTlhYjZiYTJlYThlZmFiY2QxYzQ2YWIyYTEwMWUxMmYzODNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PXmESjwph0C2v3Hs6-2m2zOTpB3q2wIfEGti_gAxvso">

Contacted.
Recreated container, and it worked fine.
Unknown reason.

**Comment by hlf20010508** [comment]
Update, it was indentation problem.
![image](https://github.com/hlf20010508/telegram-onedrive/assets/76218469/b40df18a-92a4-4449-bc8d-75a23f6a10b2)
