### ISSUE TITLE
Onedrive authorization failed.

### ISSUE THREAD

**Issue by Abelboby** [hlf20010508/telegram-onedrive#24]
Traceback (most recent call last):
  File "/telegram-onedrive/modules/onedrive/[session.py](https://web.telegram.org/a/session.py)", line 128, in load_session
    record = cls.db.get_current_user()
  File "/telegram-onedrive/modules/onedrive/[database.py](https://web.telegram.org/a/database.py)", line 139, in get_current_user
    self.execute(command)
  File "/telegram-onedrive/modules/onedrive/[database.py](https://web.telegram.org/a/database.py)", line 334, in execute
    self.cursor.execute(command, params)
sqlite3.OperationalError: no such table: current_user

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/telegram-onedrive/modules/handlers/[auth.py](https://web.telegram.org/a/auth.py)", line 152, in auth_handler
    onedrive.load_session()
  File "/telegram-onedrive/modules/onedrive/[init.py](https://web.telegram.org/a/init.py)", line 73, in load_session
    self.client.auth_provider.load_session()
  File "/usr/local/lib/python3.8/site-packages/onedrivesdk/auth_provider.py", line 323, in load_session
    self._session = self._session_type.load_session(**load_session_kwargs)
  File "/telegram-onedrive/modules/onedrive/[session.py](https://web.telegram.org/a/session.py)", line 142, in load_session
    raise NoSessionExecption("No session found.")
modules.onedrive.session.NoSessionExecption: No session found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/telegram-onedrive/modules/handlers/[auth.py](https://web.telegram.org/a/auth.py)", line 107, in od_auth
    onedrive.auth(code)
  File "/telegram-onedrive/modules/onedrive/[init.py](https://web.telegram.org/a/init.py)", line 57, in auth
    self.client.auth_provider.authenticate(
  File "/telegram-onedrive/modules/onedrive/_rewrite.py", line 40, in authenticate
    headers = {'Authorization' : f"Bearer {rcont['access_token']}"}
KeyError: 'access_token'

ps: idk how to set that server uri
currently i have it as 
environment:
      - server_uri=https://127.0.0.1:8080
and at onedrive i gave same as redirect uri
am i doing it wrong in any way?
please help!
      
      
![image](https://github.com/hlf20010508/telegram-onedrive/assets/136153140/f607ff5f-10d6-4f69-aaf0-906b84f9aac6)

**Comment by hlf20010508** [comment]
I just tried, and it worked fine.

The main error is this:
```py
File "/telegram-onedrive/modules/handlers/[auth.py](https://web.telegram.org/a/auth.py)", line 107, in od_auth
onedrive.auth(code)
File "/telegram-onedrive/modules/onedrive/[init.py](https://web.telegram.org/a/init.py)", line 57, in auth
self.client.auth_provider.authenticate(
File "/telegram-onedrive/modules/onedrive/_rewrite.py", line 40, in authenticate
headers = {'Authorization' : f"Bearer {rcont['access_token']}"}
KeyError: 'access_token'
```

Possible reason is your network problem.
You can remove container and try several times.

If this doesn't work, I'll help you further.
