### ISSUE TITLE
transfer.py error

### ISSUE THREAD

**Issue by wangkingsten** [hlf20010508/telegram-onedrive#6]
Error: Traceback (most recent call last):
  File "/telegram-onedrive/modules/handlers/transfer.py", line 27, in transfer_handler
    if message.media:
AttributeError: 'NoneType' object has no attribute 'media'

Looks like it doesn't recognize the media sent by telegram.

this is the examples from telethon  

  # Get 0 photos and print the total to show how many photos there are
                from telethon.tl.types import InputMessagesFilterPhotos
                photos = await client.get_messages(chat, 0, filter=InputMessagesFilterPhotos)
                print(photos.total)

                # Get all the photos
                photos = await client.get_messages(chat, None, filter=InputMessagesFilterPhotos)

                # Get messages by ID:
                message_1337 = await client.get_messages(chat, ids=1337)

**Comment by hlf20010508** [comment]
你发送了什么样的文件类型？
你还是用的商业账户吗？

**Comment by wangkingsten** [comment]
> 你发送了什么样的文件类型？ 你还是用的商业账户吗？

各种文件类型都尝试了，都不行
准确来说是教育账户
但这似乎和报错没有关系。
因为我这次参考了Zfile的认证配置https://docs.zfile.vip/example/onedrive
我的教育账户可以在Zfile正常运行，所以我用了他们的app_id和clientSecret
并将返回的code post给了[auth_server.py](https://github.com/hlf20010508/telegram-onedrive/blob/master/server/auth_server.py)，我认为OneDrive的认证应该是没问题的。我现在用个人账户尝试一下

**Comment by hlf20010508** [comment]
你发送的图片有document属性但没有media属性，我没有碰到过。
我需要更详细的文件信息，后缀名，文件大小。

**Comment by wangkingsten** [comment]
我只是转发了图片和自己上传了图片
您自己部署的容器在运行吗，可以让我发图片测试吗

**Comment by hlf20010508** [comment]
> > 你发送了什么样的文件类型？ 你还是用的商业账户吗？
> 
> 
> 
> 各种文件类型都尝试了，都不行
> 
> 准确来说是教育账户
> 
> 但这似乎和报错没有关系。
> 
> 因为我这次参考了Zfile的认证配置https://docs.zfile.vip/example/onedrive
> 
> 我的教育账户可以在Zfile正常运行，所以我用了他们的app_id和clientSecret
> 
> 并将返回的code post给了[auth_server.py](https://github.com/hlf20010508/telegram-onedrive/blob/master/server/auth_server.py)，我认为OneDrive的认证应该是没问题的。我现在用个人账户尝试一下
> 
> 
> 
> 

都是Business Account。
这个目前都还不支持的。
个人账号应该没问题，我自己这边一切正常。

**Comment by hlf20010508** [comment]
网页认证不会有问题，但是代码里少了几行针对商业账户的认证。
这些报错都是因为代码里的认证没过。
我的Bot设置了用户识别，你没法测试的。

**Comment by wangkingsten** [comment]
我的个人账户依旧是相同的问题
![image](https://github.com/hlf20010508/telegram-onedrive/assets/25920857/2de3c0f5-bc73-4fa5-883f-2bc63aa223b6)
![image](https://github.com/hlf20010508/telegram-onedrive/assets/25920857/a930ce73-cbf3-427c-a42d-756e258211e0)
Error: Traceback (most recent call last):
  File "/telegram-onedrive/modules/handlers/transfer.py", line 27, in transfer_handler
    if message.media:
AttributeError: 'NoneType' object has no attribute 'media'

您是部署在win10上面对吧，我是在Linux上，有没有可能是这两个操作系统的差异？

**Comment by wangkingsten** [comment]
> 网页认证不会有问题，但是代码里少了几行针对商业账户的认证。 这些报错都是因为代码里的认证没过。 我的Bot设置了用户识别，你没法测试的。

认证成功的结果后获得AccessToken和RefreshToken，这两个Token应该是通用的，我的商业账户在zfile那里获得了这两个Token,用在了您的项目里面，结果是不行的。
我的个人账户按照README的步骤操作下来也是不行的

**Comment by hlf20010508** [comment]
我是部署在服务器上的，也是linux。
你创建的群是否是按照最新的readme里面描述的步骤创建？
如果不是，那重新创建后再试一下。
如果是，我需要你发送的图片的详细信息，比如后缀，文件大小。
另外你有没有尝试过转发视频？
我没有碰到过带有document属性却没有media属性的文件，所以这个挺麻烦。

**Comment by hlf20010508** [comment]
群的创建步骤在最新readme的Usage -> Before Start里。
你这个报错跟 #4 里那个人的问题一样，是创建群的时候提前把bot加进去了。
你需要先创建一个只有你一个人的空群，然后到你的bot主页里面点加入群，这样就能正常使用了。

**Comment by wangkingsten** [comment]
> 群的创建步骤在最新readme的Usage -> Before Start里。 你这个报错跟 #4 里那个人的问题一样，是创建群的时候提前把bot加进去了。 你需要先创建一个只有你一个人的空群，然后到你的bot主页里面点加入群，这样就能正常使用了。
OK 我知道了，其实我之前没有给
![image](https://github.com/hlf20010508/telegram-onedrive/assets/25920857/d21b8e65-f38a-42cf-b2b3-e2ecaec20a6d)
这两个权限，给了之后，个人用户正常运行

但是商业版出现新的报错，应该就是你所说的有关商业版的认证代码

Error: Traceback (most recent call last):
  File "/telegram-onedrive/modules/handlers/transfer.py", line 45, in transfer_handler
    onedrive.stream_upload(buffer, name)
  File "/telegram-onedrive/modules/onedrive.py", line 93, in stream_upload
    request.send(data=buffer)
  File "/usr/local/lib/python3.8/site-packages/onedrivesdk/request_base.py", line 132, in send
    self._client.auth_provider.authenticate_request(self)
  File "/telegram-onedrive/modules/onedrive.py", line 26, in authenticate_request
    raise RuntimeError("""Session must be authenticated
RuntimeError: Session must be authenticated 
            before applying authentication to a request.

**Comment by wangkingsten** [comment]
![](https://user-images.githubusercontent.com/25920857/279875824-d21b8e65-f38a-42cf-b2b3-e2ecaec20a6d.png)
这两个权限不给的话，个人用户也无法运行
看来仅仅给BOT删除信息的权限是不够的

**Comment by hlf20010508** [comment]
> 
> 
> ![](https://user-images.githubusercontent.com/25920857/279875824-d21b8e65-f38a-42cf-b2b3-e2ecaec20a6d.png)
> 
> 这两个权限不给的话，个人用户也无法运行
> 
> 看来仅仅给BOT删除信息的权限是不够的
> 
> 

这么奇怪吗？
但是我这边不需要呀。
![image](https://github.com/hlf20010508/telegram-onedrive/assets/76218469/c6d656f9-d72a-4a52-8438-8d81ec14e4a4)

**Comment by wangkingsten** [comment]
我按照你这个权限试一下&nbsp;


Pwn!
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年11月2日(星期四) 下午2:13
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [hlf20010508/telegram-onedrive] transfer.py error (Issue #6)





  

 
这两个权限不给的话，个人用户也无法运行
 
看来仅仅给BOT删除信息的权限是不够的
  
这么奇怪吗？
 但是我这边不需要呀。

**Comment by wangkingsten** [comment]
除了第一项Change Group Info默认开启无法关闭之外，其他和你的一样，是可行的
就蛮奇怪
![image](https://github.com/hlf20010508/telegram-onedrive/assets/25920857/92d99d25-4b6f-48d5-9232-e54be4ffa64e)
之前的设置是这样的，不行

**Comment by hlf20010508** [comment]
哦telegram更新了。
现在先创建群组再拉bot，和创建群组时拉bot，我测试了一下，创建的群组类型一样了，都是super-group，本质是channel。
以前后者是basic-group，本质是chat。
导致代码会出问题。

**Comment by hlf20010508** [comment]
我之后又得改下说明了。

**Comment by wangkingsten** [comment]
> 我之后又得改下说明了。

辛苦大佬

**Comment by hlf20010508** [comment]
你好，现在bot支持开发者账户了，但是还没有测试过商业账户。
如果你有时间的话可以试一下，需要重新创建容器。
镜像使用dev版`hlf01/telegram-onedrive:dev`

**Comment by hlf20010508** [comment]
在Azure portal中创建应用时`Supported account types`需要选择`Accounts in any organizational directory and personal Microsoft accounts`，其他操作与个人账户相同。
如果你将OneDrive的`session`保存在`volume`里，需要删除它。之后我会尝试更新一下OneDrive注销的命令，以及支持多个OneDrive账号。

**Comment by hlf20010508** [comment]
已经确定你的A1Pro账户是官方不支持调用API的，我自己申请的A1账户也不行，只有拥有API调用权限的账户类型才行。
各账户类型权限看[OFFICE365各版本、A1、A1P、E3、E5等版本科普](https://shikey.com/2019/12/24/office365-versions-a1-a1p-e3-etc.html)以及[官方文档](https://learn.microsoft.com/zh-cn/office365/servicedescriptions/office-365-service-descriptions-technet-library)。
如果你想免费使用1T空间，建议自行申请E5开发者账号，支持调用API。

**Comment by wangkingsten** [comment]
E5账户你尝试了吗，我上次试了试也是一样的

**Comment by hlf20010508** [comment]
新版已经支持了

**Comment by wangkingsten** [comment]
感谢

**Comment by wangkingsten** [comment]
Error: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 496, in _make_request
    conn.request(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 409, in request
    self.send(chunk)
  File "/usr/local/lib/python3.8/http/client.py", line 972, in send
    self.sock.sendall(data)
  File "/usr/local/lib/python3.8/ssl.py", line 1204, in sendall
    v = self.send(byte_view[count:])
  File "/usr/local/lib/python3.8/ssl.py", line 1173, in send
    return self._sslobj.write(data)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 844, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/retry.py", line 470, in increment
    raise reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 496, in _make_request
    conn.request(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 409, in request
    self.send(chunk)
  File "/usr/local/lib/python3.8/http/client.py", line 972, in send
    self.sock.sendall(data)
  File "/usr/local/lib/python3.8/ssl.py", line 1204, in sendall
    v = self.send(byte_view[count:])
  File "/usr/local/lib/python3.8/ssl.py", line 1173, in send
    return self._sslobj.write(data)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/telegram-onedrive/modules/handlers/transfer.py", line 31, in transfer_handler
    await multi_parts_uploader(tg_client, message.media.document, name, progress_callback=callback)
  File "/telegram-onedrive/modules/transfer.py", line 66, in multi_parts_uploader
    await onedrive.multipart_upload(uploader, buffer, pre_offset)
  File "/telegram-onedrive/modules/onedrive.py", line 129, in multipart_upload
    uploader.post(offset, part_size, buffer)
  File "/telegram-onedrive/modules/onedrive.py", line 277, in post
    return self.request(begin, length, buffer, options).post()
  File "/telegram-onedrive/modules/onedrive.py", line 223, in post
    entity = UploadSession(json.loads(self.send(data=self._buffer).content))
  File "/usr/local/lib/python3.8/site-packages/onedrivesdk/request_base.py", line 147, in send
    response = self._client.http_provider.send(
  File "/usr/local/lib/python3.8/site-packages/onedrivesdk/http_provider.py", line 69, in send
    response = session.send(prepped)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))


依旧是错误捏

**Comment by hlf20010508** [comment]
这个错误应该是网络问题，你再试试。商业版账号只是不支持/url，别的都是支持的

**Comment by wangkingsten** [comment]
换了一台VPS成功了！

**Comment by hlf20010508** [comment]
好的
